### ISSUE TITLE
viewport makes the site hard to read on mobile

### ISSUE THREAD

**Issue by jyn514** [rust-lang/foundation.rust-lang.org#29]
Either it shows a bunch of blank space:

![Screenshot_20210208-125907_Firefox](https://user-images.githubusercontent.com/23638587/107261796-bf356a00-6a0d-11eb-8475-a8bd4f83f6cd.jpg)

Or it's far too zoomed in:
![Screenshot_20210208-130229_Firefox](https://user-images.githubusercontent.com/23638587/107261956-f7d54380-6a0d-11eb-99c4-5bd117678da4.jpg)

**Comment by reiner-dolp** [comment]
The root cause for this is that some CSS is not responsive. One of your screenshots is scaled to the HTML body width, the other to the widest child element (which all have white font color and thus make that space look empty):

- the navigation cannot wrap into multiple lines because of `display: table-row`
- the large font size makes the word "Foundation" in headings wider than the screen

@ashleygwilliams I would be happy to provide some dev hours if this website is not just a placeholder.

**Comment by ashleygwilliams** [comment]
solved by #30

**Comment by ashleygwilliams** [comment]
(to clarify, this solves the viewport issue, the site was not built to be fully mobile, it will develop over time i suspect! if you want to file a PR go for it!)
